backend:
  name: git-gateway
  branch: main
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.md"
        label: "Home"
        name: "home"
      - file: "content/services.md"
        label: "Services"
        name: "services"
      - file: "content/about.md"
        label: "About"
        name: "about"
      - file: "content/pricing.md"
        label: "Pricing"
        name: "pricing"
      - file: "content/contact.md"
        label: "Contact"
        name: "contact"
      - file: "content/faq.md"
        label: "FAQ"
        name: "faq"
  - name: "posts"
    label: "Case Studies"
    folder: "content/case-studies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
